### ISSUE TITLE
Benchmarks core dump on atoi()

### ISSUE THREAD

**Issue by mratsim** [rkuchumov/workstealing_threadpool#3]
On the `fib` `blkmul` and `dfs` benchmarks I get atoi crash when launching the bench with no arguments.

Here is the backtrace

```gdb
(gdb) bt
#0  0x00007ffff7a92e9a in ____strtoll_l_internal () from /usr/lib/libc.so.6
#1  0x0000555555556168 in atoi (__nptr=<optimized out>) at /usr/include/stdlib.h:363
#2  main (argc=0, argv=0x7fffffffda40) at <...>/staccato/benchmarks/staccato/fib/main.cpp:49
```

Using GCC 9.1.0 ang glibc 2.29

**Comment by mratsim** [comment]
Compiling with Intel ICC works:

```
Scheduler:  staccato
Benchmark:  fib
Threads:    36
Time(us):   179163
Input:      40
Output:     102334155
```
